version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: game
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  pgboss-ui:
    image: imochoa/pg-boss-ui:latest
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/game
      SCHEMA: pgboss
    ports:
      - "3010:3010"
    depends_on:
      - db
volumes:
  db_data:


