app = "bigdustry-2-api"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]

[checks]
  [checks.health]
    type = "http"
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/health"


